-- PastPaperZone: required Supabase tables for analytics, reports and saved papers.
-- Run this once in Supabase Dashboard -> SQL Editor.
-- Existing tables are left intact by CREATE TABLE IF NOT EXISTS.

create table if not exists public.paper_activity (
  id bigint generated by default as identity primary key,
  action text not null check (action in ('visit','view','download','signup')),
  subject_id text,
  year text,
  medium text,
  doc_type text,
  user_id uuid references auth.users(id) on delete set null,
  visitor_id text,
  created_at timestamptz not null default now()
);

create index if not exists paper_activity_created_at_idx
  on public.paper_activity (created_at desc);
create index if not exists paper_activity_action_created_at_idx
  on public.paper_activity (action, created_at desc);

create table if not exists public.paper_reports (
  id bigint generated by default as identity primary key,
  subject_id text not null,
  year text not null,
  medium text not null,
  doc_type text not null,
  reason text not null,
  details text,
  status text not null default 'pending'
    check (status in ('pending','resolved','dismissed')),
  user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists paper_reports_status_created_at_idx
  on public.paper_reports (status, created_at desc);

create table if not exists public.saved_papers (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  subject_id text not null,
  year text not null,
  medium text not null,
  doc_type text not null,
  created_at timestamptz not null default now(),
  unique (user_id, subject_id, year, medium, doc_type)
);

create index if not exists saved_papers_user_created_at_idx
  on public.saved_papers (user_id, created_at desc);

alter table public.saved_papers enable row level security;

drop policy if exists "Users can read their saved papers" on public.saved_papers;
create policy "Users can read their saved papers"
  on public.saved_papers for select
  using (auth.uid() = user_id);

drop policy if exists "Users can insert their saved papers" on public.saved_papers;
create policy "Users can insert their saved papers"
  on public.saved_papers for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can delete their saved papers" on public.saved_papers;
create policy "Users can delete their saved papers"
  on public.saved_papers for delete
  using (auth.uid() = user_id);
